version: "3.8"
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: build/api/Dockerfile
    init: true
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./build/api/php.ini:/usr/local/etc/php/conf.d/local.ini
  db:
    container_name: db
    build:
      context: ./
      dockerfile: build/db/Dockerfile
    init: true
    volumes:
      - dbdata:/var/lib/mysql
      - ./build/db/conf/my.cnf:/etc/mysql/my.cnf
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: logmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  ws:
    container_name: ws
    build:
      context: ./
      dockerfile: build/ws/Dockerfile
    init: true
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www/
      - ./build/ws/conf/:/etc/nginx/conf.d/

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
